version: "3.9"
services:
  openresume:
    container_name: OpenResume
    image: peppershade/open-resume:latest
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 6155:3000